version: "2"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  judge-server:
    image: smilingthrone13/judge0-custom:v1
    links:
      - db
      - redis
      - judge-worker
    command: ["./scripts/server"]
    volumes:
      - ./config/judge0.conf:/judge0.conf:ro
    ports:
      - ":2358"
    privileged: true
    <<: *default-logging
    restart: always

  judge-worker:
    image: smilingthrone13/judge0-custom:v1
    links:
      - db
      - redis
    command: ["./scripts/workers"]
    volumes:
      - ./config/judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:13.0
    env_file: config/judge0.conf
    volumes:
      - judge-postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: config/judge0.conf
    volumes:
      - judge-redis-data:/data
    <<: *default-logging
    restart: always


  lcode-db:
    image: postgres:16-alpine
    volumes:
      - lcode-postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lcode
    <<: *default-logging
    restart: always

  lcode:
    image: smilingthrone13/lcode_back:v1
    links:
      - lcode-db
      - judge-server
    volumes:
      - ./config:/config:ro
      - ./files:/files
      - docs-data:/docs
    environment:
      - PATH_DB=postgres://postgres:postgres@lcode-db:5432/lcode
    ports:
      - "5000:5000"
    privileged: true
    <<: *default-logging
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    links:
      - lcode
    ports:
      - "8082:8080"
    volumes:
      - docs-data:/docs
    environment:
      SWAGGER_JSON: /docs/api.yaml
    <<: *default-logging
    restart: always

volumes:
  judge-postgres-data:
  judge-redis-data:
  lcode-postgres-data:
  docs-data:
