isDebug: true
corsOrigins: [ "*" ]
http:
  host: localhost
  port: 5000
  maxHeaderBytes: 1
  readTimeout: 600s
  writeTimeout: 600s
tls:
  enabled: false
  cert: C:\Users\l.konstantin\Documents\Projects\!ssl_certs\cert.pem
  key: C:\Users\l.konstantin\Documents\Projects\!ssl_certs\key.pem
searchCoefficient: 0.3
auth:
  accessTokenExpTime: 300s  # seconds
  refreshTokenExpTime: 720h # hours 720h
  secret: test-secret # any string