isDebug: true
corsOrigins: [ "*" ]
http:
  host: 0.0.0.0
  port: 5000
  maxHeaderBytes: 1
  readTimeout: 600s
  writeTimeout: 600s
tls:
  enabled: false
  cert: C:\Users\l.konstantin\Documents\Projects\!ssl_certs\cert.pem
  key: C:\Users\l.konstantin\Documents\Projects\!ssl_certs\key.pem
searchCoefficient: 0.25
auth:
  accessTokenExpTime: 300s  # seconds
  refreshTokenExpTime: 720h # hours 720h
  secret: test-secret # any string
judge:
  host: judge-server
  port: 2358
  defaultMemoryLimitKB: 128000
  defaultTimeLimitSec: 5.0
files:
  mainFolder: .\files
  userAvatarMaxSize: 5MB # 5MB